// Via https://www.jeremiak.com/blog/block-bots-netlify-edge-functions/
// inspired (and taken) from ethan marcotte's blog post
// https://ethanmarcotte.com/wrote/blockin-bots/
const botUas = [
	'AddSearchBot',
	'AgentTimes',
	'AI2Bot',
	'AI2Bot-DeepResearchEval',
	'Ai2Bot-Dolma',
	'aiHitBot',
	'AIWebIndex',
	'amazon-kendra',
	'amazon-QBusiness',
	'Amazonbot',
	'AmazonBuyForMe',
	'Amzn-SearchBot',
	'Amzn-User',
	'Andibot',
	'Anomura',
	'anthropic-ai',
	'ApifyBot',
	'ApifyWebsiteContentCrawler',
	'Applebot',
	'Applebot-Extended',
	'Aranet-SearchBot',
	'atlassian-bot',
	'Awario',
	'AzureAI-SearchBot',
	'bedrockbot',
	'bigsur.ai',
	'Bravebot',
	'Brightbot',
	'Brightbot 1.0',
	'BuddyBot',
	'Bytespider',
	'CCBot',
	'Channel3Bot',
	'ChatGLM-Spider',
	'ChatGPT Agent',
	'ChatGPT-User',
	'Claude-Code',
	'Claude-SearchBot',
	'Claude-User',
	'Claude-Web',
	'ClaudeBot',
	'Cloudflare-AutoRAG',
	'CloudVertexBot',
	'Code',
	'cohere-ai',
	'cohere-training-data-crawler',
	'Cotoyogi',
	'CragCrawler',
	'Crawl4AI',
	'Crawlspace',
	'Cursor',
	'Datenbank Crawler',
	'DeepSeekBot',
	'Devin',
	'Diffbot',
	'DuckAssistBot',
	'Echobot Bot',
	'EchoboxBot',
	'ExaBot',
	'FacebookBot',
	'facebookexternalhit',
	'Factset_spyderbot',
	'FirecrawlAgent',
	'FriendlyCrawler',
	'GeistHaus-PageFetcher',
	'Gemini-Deep-Research',
	'Google-Agent',
	'Google-CloudVertexBot',
	'Google-Extended',
	'Google-Firebase',
	'Google-Gemini-CLI',
	'Google-NotebookLM',
	'GoogleAgent-Mariner',
	'GoogleAgent-URLContext',
	'GoogleOther',
	'GoogleOther-Image',
	'GoogleOther-Video',
	'GPTBot',
	'HenkBot',
	'iAskBot',
	'iaskspider',
	'iaskspider/2.0',
	'ICC-Crawler',
	'ImagesiftBot',
	'imageSpider',
	'img2dataset',
	'ISSCyberRiskCrawler',
	'kagi-fetcher',
	'Kangaroo Bot',
	'Kimi-User',
	'KlaviyoAIBot',
	'KunatoCrawler',
	'laion-huggingface-processor',
	'LAIONDownloader',
	'LCC',
	'LinerBot',
	'Linguee Bot',
	'LinkupBot',
	'Manus-User',
	'meta-externalagent',
	'Meta-ExternalAgent',
	'meta-externalfetcher',
	'Meta-ExternalFetcher',
	'meta-webindexer',
	'MistralAI-User',
	'MistralAI-User/1.0',
	'Mozilla-Tabstack',
	'MyCentralAIScraperBot',
	'NagetBot',
	'netEstate Imprint Crawler',
	'newsai',
	'NotebookLM',
	'NovaAct',
	'OAI-SearchBot',
	'omgili',
	'omgilibot',
	'OpenAI',
	'opencode',
	'Operator',
	'PanguBot',
	'Panscient',
	'panscient.com',
	'Perplexity-User',
	'PerplexityBot',
	'PetalBot',
	'PhindBot',
	'Poggio-Citations',
	'Poseidon Research Crawler',
	'QualifiedBot',
	'Querit-SearchBot',
	'QueritBot',
	'QuillBot',
	'quillbot.com',
	'SBIntuitionsBot',
	'Scrapy',
	'SemrushBot-OCOB',
	'SemrushBot-SWA',
	'Shap-User',
	'ShapBot',
	'Sidetrade indexer bot',
	'Spider',
	'TavilyBot',
	'Terra Cotta',
	'TerraCotta',
	'Thinkbot',
	'TikTokSpider',
	'Timpibot',
	'TongyiBot',
	'Trae',
	'TwinAgent',
	'UseAI',
	'VelenPublicWebCrawler',
	'WARDBot',
	'Webzio-Extended',
	'webzio-extended',
	'wpbot',
	'WRTNBot',
	'YaK',
	'YandexAdditional',
	'YandexAdditionalBot',
	'YiyanBot',
	'YouBot',
	'ZanistaBot'
]

export default async (request, context) => {
	const ua = request.headers.get('user-agent');

	// Block requests with a missing or empty User-Agent — common for abusive
	// scrapers, and calling .toLowerCase() on a null UA would throw.
	if (!ua || ua.trim() === '') {
		return new Response(null, { status: 401 });
	}

	const lowerUa = ua.toLowerCase();
	const isBot = botUas.some(u => lowerUa.includes(u.toLowerCase()));

	const response = isBot ? new Response(null, { status: 401 }) : await context.next();
	return response
};

// Path declaration lives here (not in netlify.toml) so we can attach a
// rateLimit rule. This catches abusive traffic regardless of User-Agent:
// no human requests 60+ pages a minute.
export const config = {
	path: "/*",
	rateLimit: {
		windowLimit: 60,   // requests...
		windowSize: 60,    // ...per 60s per IP (max window 180s)
		aggregateBy: ["ip", "domain"],
		// action defaults to "block" → HTTP 429
	},
};
